# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.5'
    branches:
      only:
        - master
    working_directory: ~/repo
    environment:
        JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "gradle.properties" }}
            - v1-gradle-cache-

      - run:
          name: Gradle dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-gradle-cache-{{ checksum "gradle.properties" }}

      - run:
          name: Run tests
          command: ./gradlew clean test

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/libs
          destination: libs

workflows:
  build_workflow:
    jobs:
      - build