# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0 
    steps:
      - checkout  # Pull down your code

      # Restore Gradle dependencies (caches between builds for speed)
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ checksum "gradle.properties" }}
            - v1-gradle-cache-

      - run:
          name: Gradle dependencies
          command: ./gradlew dependencies

      # Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-gradle-cache-{{ checksum "gradle.properties" }}

      # Build & test
      - run:
          name: Run tests
          command: ./gradlew clean test

      # Collect test results (Junit XML) so CircleCI can show them
      - store_test_results:
          path: build/test-results/test

      # Optionally store build artifacts (e.g., JARs, coverage reports)
      - store_artifacts:
          path: build/libs
          destination: libs

workflows:
  build_workflow:
    jobs:
      - build-and-test